package com.flyingtechs.studentManagement.controller.impl;

import com.flyingtechs.studentManagement.dto.CourseDTO;
import com.flyingtechs.studentManagement.model.Course;
import com.flyingtechs.studentManagement.service.CourseService;
import com.flyingtechs.userManagement.controller.impl.CustomUtils;
import org.hamcrest.Matchers;
import org.hamcrest.core.Is;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.util.Arrays;

@SpringBootTest
@AutoConfigureMockMvc
@RunWith(SpringRunner.class)
public class CourseControllerImplTest {
    private static final String ENDPOINT_URL = "/courses";

    @InjectMocks
    private CourseControllerImpl courseController;

    @MockBean
    private CourseService courseService;

    @Autowired
    private MockMvc mockMvc;

    @Before
    public void setup() {
        this.mockMvc = MockMvcBuilders.standaloneSetup(this.courseController).build();
    }

    @Test
    public void getAll() throws Exception {
        Course course1 = new Course();
        // You don't need to set the "id" as it's typically generated by the database.

        Course course2 = new Course();

        Mockito.when(courseService.findAll()).thenReturn(Arrays.asList(course1, course2));

        mockMvc.perform(MockMvcRequestBuilders.get(ENDPOINT_URL))
                .andExpect(MockMvcResultMatchers.status().isOk())
                .andExpect(MockMvcResultMatchers.content()
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(MockMvcResultMatchers.jsonPath("$", Matchers.hasSize(2)));

    }

    @Test
    public void getById() throws Exception {
        Course course = new Course();
        // You don't need to set the "id" here.

        Mockito.when(courseService.findById(ArgumentMatchers.anyLong())).thenReturn(java.util.Optional.of(course));

        mockMvc.perform(MockMvcRequestBuilders.get(ENDPOINT_URL + "/1"))
                .andExpect(MockMvcResultMatchers.status().isOk())
                .andExpect(MockMvcResultMatchers.content()
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(MockMvcResultMatchers.jsonPath("$.id", Is.is(0))); // Modify this path according to your actual DTO structure.
        Mockito.verify(courseService, Mockito.times(1)).findById(1L);
        Mockito.verifyNoMoreInteractions(courseService);
    }

    @Test
    public void save() throws Exception {
        Course course = new Course();
        // You don't need to set the "id" here.

        Mockito.when(courseService.save(ArgumentMatchers.any(Course.class))).thenReturn(course);

        mockMvc.perform(
                        MockMvcRequestBuilders.post(ENDPOINT_URL)
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(CustomUtils.asJsonString(new CourseDTO(course)))
                                .accept(MediaType.APPLICATION_JSON))
                .andExpect(MockMvcResultMatchers.status().isCreated());
        Mockito.verify(courseService, Mockito.times(1)).save(ArgumentMatchers.any(Course.class));
        Mockito.verifyNoMoreInteractions(courseService);
    }

    @Test
    public void update() throws Exception {
        Course course = new Course();
        // You don't need to set the "id" here.

        Mockito.when(courseService.update(ArgumentMatchers.any(), ArgumentMatchers.anyLong())).thenReturn(course);

        mockMvc.perform(
                        MockMvcRequestBuilders.put(ENDPOINT_URL + "/1")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(CustomUtils.asJsonString(new CourseDTO(course)))
                                .accept(MediaType.APPLICATION_JSON))
                .andExpect(MockMvcResultMatchers.status().isOk());
        Mockito.verify(courseService, Mockito.times(1)).update(ArgumentMatchers.any(Course.class), ArgumentMatchers.anyLong());
        Mockito.verifyNoMoreInteractions(courseService);
    }

    @Test
    public void delete() throws Exception {
        Mockito.doNothing().when(courseService).deleteById(ArgumentMatchers.anyLong());
        mockMvc.perform(
                        MockMvcRequestBuilders.delete(ENDPOINT_URL + "/1"))
                .andExpect(MockMvcResultMatchers.status().isOk());
        Mockito.verify(courseService, Mockito.times(1)).deleteById(ArgumentMatchers.anyLong());
        Mockito.verifyNoMoreInteractions(courseService);
    }
}